name: traccar_client_sdk
description: "Flutter plugin for background location tracking. Wraps the Traccar Client SDK for Android and iOS."
version: 0.0.25
repository: https://github.com/traccar/traccar-client-sdk

environment:
  sdk: ^3.11.5
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.traccar.traccar_client_sdk
        pluginClass: TraccarClientSdkPlugin
      ios:
        pluginClass: TraccarClientSdkPlugin
